application: big-data-collection
version: 1
runtime: python27
api_version: 1
threadsafe: true

automatic_scaling:
  max_idle_instances: 1
  max_pending_latency: 10s

handlers:

- url: .*
  script: main.app

libraries:
- name: pycrypto
  version: "latest"

- name: ssl
  version: latest